version: '3.9'

services:
  db:
    image: "postgres:16.1-alpine"
    container_name: skilltribe-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=skilltribe
    ports:
      - "5432:5432"